[workspace]
preview = ["pixi-build"]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge","https://conda.modular.com/max"]
description = "Bindings for SDL3 in Mojo"
name = "sdl-mojo"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
fmt = "mojo format -l 1000 src"
gen = "python3 gen.py"
pkg = "mojo package src -o test/sdl.ðŸ“¦"
build = {depends-on = ["gen", "fmt", "pkg"]}
test = { cmd = "mojo test/test.mojo", depends-on = ["pkg"] }
temp = "mojo temp.mojo"

[package]
name = "sdl-mojo"
version = "0.1.0"

[package.build.config.pkg]
name = "sdl"

[package.build.backend]
name="pixi-build-mojo"
version = "0.1.*"

[package.host-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26"

[package.build-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26"

[package.run-dependencies]
mojo-compiler = ">=0.25.7.0,<0.26"
sdl3 = ">=3.2.26,<4"

[dependencies]
mojo = ">=0.25.7.0,<0.26"
sdl3 = ">=3.2.26,<4"
python = ">=3.14.0,<3.15"
