[workspace]
authors = ["helehex <helehex@gmail.com>"]
channels = ["conda-forge", "https://conda.modular.com/max-nightly"]
description = "Bindings for SDL3 in Mojo"
name = "sdl-mojo"
platforms = ["linux-64", "linux-aarch64", "osx-arm64"]
version = "0.1.0"

[tasks]
fmt = "mojo format -l 1000 out"
gen = "python3 gen.py"
pkg = "mojo package out -o test/sdl.ðŸ“¦"
build = {depends-on = ["gen", "fmt", "pkg"]}
test = { cmd = "mojo test/test.mojo", depends-on = ["pkg"] }
temp = "mojo temp.mojo"

[dependencies]
mojo = ">=0.26.1.0.dev2025111705,<0.27"
sdl3 = ">=3.2.26,<4"
python = ">=3.14.0,<3.15"
